spring.application.name=AnimeStore

# Server Port
server.port=8080

# Basic Auth Credentials (Task 3)
spring.security.user.name=animeadmin
spring.security.user.password=secret123
spring.security.user.roles=ADMIN

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/animestore_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Pretty JSON
spring.jackson.serialization.indent-output=true
